name: NPM build and push

on:
  release:
    types: [released]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 22
            registry-url: https://registry.npmjs.org/
            package-manager-cache: false  # never use caching in release builds
        - run: npm install -g npm@latest
        - run: npm install -g yarn
        - run: yarn install
        - run: yarn build
        - run: npm publish --access public
